# Set paths
STAN_HOME <- file.path("inst", "stan")
FILES <- c(
  "_common/functions-utils.stan",
  "_common/functions-kernels.stan",
  "_common/functions-prior.stan"
)

if (length(FILES) > 0) {
  # Create Stan model containing only a functions block with all the functions
  two_spaces <- "  " 
  f_list <- lapply(file.path(STAN_HOME, FILES), FUN = readLines)
  functions <- paste(unlist(f_list), collapse = paste0("\n", two_spaces))
  functions <- paste0(two_spaces, functions)
  model_code <- paste(c("functions {", functions, "}"), collapse = "\n")
  header <- "// Automatically generated by dev-cpp.R\n\n"
  model_code <- paste0(header, model_code, "\n")
  
  # Write Stan code to file
  fn <- file.path(STAN_HOME, 'all_functions.stan')
  cat(model_code, file = fn)
  
  # Transpile to C++ code
  cpp_code <- rstan::expose_stan_functions(fn, verbose = TRUE, dryRun = TRUE)
  file.remove(fn)
  
  # Remove an include to prevent linker error
  cpp_lines <- scan(text = cpp_code, what = character(), sep = "\n", quiet = TRUE)
  line_idx <- which(cpp_lines == "#include <exporter.h>")
  cpp_lines[line_idx] <- "// REMOVED #include <exporter.h> by dev-cpp.R "
  cpp_code <- paste0(cpp_lines, collapse = "\n")
  cpp_code <- paste0(cpp_code, "\n")
  
  # Write the C++ code to src/stanFunctions.cpp
  cat(cpp_code, file = file.path('src', 'stanFunctions.cpp'))
  
  # Update R/RcppExports.R and src/RcppExports.cpp
  Rcpp::compileAttributes(pkgdir = '.', verbose = TRUE)
}
