---
title: "Basic usage of the lgpr package"
author: "Juho Timonen"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
#  pdf_document:
#    toc: true     
vignette: >
  %\VignetteIndexEntry{Basic usage of the lgpr package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "##"
)
```

This vignette demonstrates how to model a longitudinal data set and perform covariate selection using the `lgp` function of the `lgpr` package. In the example cases, the number of data points is small enough so that the experiments can be run in just a few seconds.

```{r load}
library("lgpr")
set.seed(123)
```

## Example

```{r example, fig.width=6.6, fig.height=4}

# generate artificial data --------------------------------------------------

simData <- simulate_data(N           = 8,
                        t_data       = seq(6, 30, by = 6),
                        covariates   = c(    2,2),
                        lengthscales = c(6,6,6,6),
                        relevances   = c(1,1,1,0),
                        names        = c("sex", "location"),
                        t_jitter     = 0.5,
                        snr          = 5)

data <- simData$data
plot_simdata(simData, componentwise = F)
plot_simdata(simData, componentwise = T)

# create and fit a model --------------------------------------------------

fit <- lgp(formula  = y ~ id + age + sex + location,
           data     = data,
           iter     = 1000, 
           chains   = 1)

# visualization -----------------------------------------------------------

plot(fit)
plot_components(fit)

# prediction --------------------------------------------------------------

t_test <- seq(0, 40, length.out = 60)
X_test <- create_test_points(fit, t_test)
PRED   <- lgp_predict(fit, X_test, samples = "mean")
plot_posterior_y(fit, PRED, uncertainty = "errorbar")

```

