# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

STAN_check_real_positive <- function(a, pstream__ = 0L) {
    invisible(.Call(`_lgpr_STAN_check_real_positive`, a, pstream__))
}

STAN_check_prob_positive <- function(a, pstream__ = 0L) {
    invisible(.Call(`_lgpr_STAN_check_prob_positive`, a, pstream__))
}

STAN_warp_input <- function(x, a, pstream__ = 0L) {
    .Call(`_lgpr_STAN_warp_input`, x, a, pstream__)
}

STAN_var_mask <- function(x, a, pstream__ = 0L) {
    .Call(`_lgpr_STAN_var_mask`, x, a, pstream__)
}

STAN_expand <- function(v, idx_expand, pstream__ = 0L) {
    .Call(`_lgpr_STAN_expand`, v, idx_expand, pstream__)
}

STAN_edit_dis_age <- function(x_dis_age, idx_expand, teff_obs, teff, pstream__ = 0L) {
    .Call(`_lgpr_STAN_edit_dis_age`, x_dis_age, idx_expand, teff_obs, teff, pstream__)
}

STAN_kernel_base_zerosum <- function(x1, x2, num_cat, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_base_zerosum`, x1, x2, num_cat, pstream__)
}

STAN_kernel_base_cat <- function(x1, x2, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_base_cat`, x1, x2, pstream__)
}

STAN_kernel_base_bin <- function(x1, x2, c, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_base_bin`, x1, x2, c, pstream__)
}

STAN_kernel_base_disease_mask <- function(x1, x2, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_base_disease_mask`, x1, x2, pstream__)
}

STAN_kernel_base_var_mask <- function(x1, x2, steepness, vm_params, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_base_var_mask`, x1, x2, steepness, vm_params, pstream__)
}

STAN_kernel_discrete <- function(x1, x2, kernel_type, num_cat, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_discrete`, x1, x2, kernel_type, num_cat, pstream__)
}

STAN_kernel_fixed <- function(x1, x2, num_levels, ctype, ktype, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_fixed`, x1, x2, num_levels, ctype, ktype, pstream__)
}

STAN_kernel_stationary <- function(K_fixed, x1, x2, ctype, alpha, ell, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_stationary`, K_fixed, x1, x2, ctype, alpha, ell, pstream__)
}

STAN_kernel_nonstationary <- function(x1, x2, alpha, ell, steepness, vm_params, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_nonstationary`, x1, x2, alpha, ell, steepness, vm_params, pstream__)
}

STAN_kernel_disease <- function(K_fixed, x1, x2, alpha, ell, wrp, beta, teff, vm_params, idx1_expand, idx2_expand, teff_obs, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_disease`, K_fixed, x1, x2, alpha, ell, wrp, beta, teff, vm_params, idx1_expand, idx2_expand, teff_obs, pstream__)
}

STAN_kernel_fixed_all <- function(n1, n2, x1, x2, num_levels, components, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_fixed_all`, n1, n2, x1, x2, num_levels, components, pstream__)
}

STAN_kernel_all <- function(n1, n2, K_fixed, components, x1, x2, alpha, ell, wrp, beta, teff, vm_params, idx1_expand, idx2_expand, teff_obs, pstream__ = 0L) {
    .Call(`_lgpr_STAN_kernel_all`, n1, n2, K_fixed, components, x1, x2, alpha, ell, wrp, beta, teff, vm_params, idx1_expand, idx2_expand, teff_obs, pstream__)
}

STAN_gp_posterior_helper <- function(Ly, K, v, pstream__ = 0L) {
    .Call(`_lgpr_STAN_gp_posterior_helper`, Ly, K, v, pstream__)
}

STAN_gp_posterior <- function(KX, y, delta, sigma, pstream__ = 0L) {
    .Call(`_lgpr_STAN_gp_posterior`, KX, y, delta, sigma, pstream__)
}

STAN_log_prior <- function(x, types, hyper, pstream__ = 0L) {
    .Call(`_lgpr_STAN_log_prior`, x, types, hyper, pstream__)
}

